apiVersion: v1
kind: Service
metadata:
  name: mongo-{{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
  selector:
    app: mongo-{{ .Release.Name }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-{{ .Release.Name }}
  labels:
    app: mongo-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: mongo-{{ .Release.Name }}
  replicas: {{ .Values.mongo.replicas }}
  template:
    metadata:
      labels:
        app: mongo-{{ .Release.Name }}

    spec:
      containers:
        - image: {{ .Values.mongo.docker.image }}:{{ .Values.mongo.docker.tag }}
          name: mongo-{{ .Release.Name }}
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.mongo.port | default 27017 }}
          volumeMounts:
            - name: mongo-{{ .Release.Name }}-storage
              mountPath: /data/db
      volumes:
        - name: mongo-{{ .Release.Name }}-storage
          persistentVolumeClaim:
            claimName: mongo-{{ .Release.Name }}-pvc